# Generated by Django 5.2.17 on 2026-08-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformainvoice',
            name='commodity',
            field=models.CharField(blank=True, default='', help_text='Free text, copied from the quotation at conversion time.', max_length=150),
        ),
    ]
