# Generated by Django 5.2.17 on 2026-08-13 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_historicalreferencedocument_referencedocument'),
        ('proforma', '0003_proformainvoice_shipment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proformainvoice',
            name='reference_number',
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='reference_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_invoices', to='masters.referencedocument'),
        ),
    ]
