# Generated by Django 6.1 on 2026-08-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_historicalreferencedocument_referencedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='website',
            field=models.CharField(blank=True, help_text='e.g. www.example.com', max_length=150),
        ),
        migrations.AddField(
            model_name='historicalcompanyinfo',
            name='website',
            field=models.CharField(blank=True, help_text='e.g. www.example.com', max_length=150),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='code',
            field=models.CharField(blank=True, help_text="Short internal code/SKU, e.g. 'FRT-AIR-001'. Shown in the item dropdown for quick lookup.", max_length=30),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='description',
            field=models.TextField(blank=True, help_text='Longer description auto-filled onto a quotation line when this item is selected (falls back to the Name above if left blank).'),
        ),
        migrations.AddField(
            model_name='item',
            name='code',
            field=models.CharField(blank=True, help_text="Short internal code/SKU, e.g. 'FRT-AIR-001'. Shown in the item dropdown for quick lookup.", max_length=30),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, help_text='Longer description auto-filled onto a quotation line when this item is selected (falls back to the Name above if left blank).'),
        ),
    ]
