# Generated by Django 5.2.17 on 2026-08-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='commodity',
            field=models.CharField(blank=True, default='', help_text='Free text, copied from the proforma invoice at invoice creation.', max_length=150),
        ),
    ]
