# Generated by Django 5.2.17 on 2026-08-11 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_alter_invoice_commodity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='shipment_type',
            field=models.CharField(blank=True, choices=[('import', 'Import'), ('export', 'Export'), ('transit', 'Transit')], max_length=10),
        ),
    ]
