# Generated by Django 5.2.17 on 2026-08-10 04:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoicing', '0001_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('invoice', 'Invoice'), ('payment', 'Payment'), ('adjustment', 'Adjustment')], max_length=15)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=0, help_text='Amount the client now owes (e.g. an invoice).', max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, help_text='Amount reducing what the client owes (e.g. a payment).', max_digits=14)),
                ('running_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='masters.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='invoicing.invoice')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='invoicing.payment')),
            ],
            options={
                'verbose_name_plural': 'Ledger Entries',
                'ordering': ['client', 'date', 'id'],
                'permissions': [],
            },
        ),
        migrations.CreateModel(
            name='StatementOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statement_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='masters.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_to', '-id'],
            },
        ),
    ]
