# Generated by Django 5.2.17 on 2026-08-07 11:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('final_destination', models.CharField(blank=True, max_length=150, verbose_name='Final Point of Delivery (FPOD)')),
                ('commodity_quantity', models.CharField(blank=True, help_text="e.g. '1', '20ft x2'", max_length=50)),
                ('commodity_unit', models.CharField(blank=True, help_text='e.g. unit, ton, CBM', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted to Proforma')], default='draft', max_length=15)),
                ('reference_number', models.CharField(blank=True, help_text="Client's own reference, if any.", max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True, help_text='Printed terms & conditions; defaults from Document Settings.')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vat_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_approved', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='masters.client')),
                ('commodity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='masters.commodity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='masters.currency')),
                ('destination_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations_as_destination', to='masters.port', verbose_name='Destination Port (POD)')),
                ('origin_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations_as_origin', to='masters.port', verbose_name='Origin Port (POL)')),
                ('payment_terms', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='masters.paymentterm')),
                ('sales_representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'permissions': [('approve_quotation', 'Can approve quotation'), ('submit_quotation', 'Can submit quotation for approval')],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('item', models.ForeignKey(blank=True, help_text='Optional link to a master Item; pre-fills description/price/VAT.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_lines', to='masters.item')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
