# Generated by Django 5.2.17 on 2026-08-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='commodity',
            field=models.CharField(blank=True, default='', help_text="Free text, e.g. 'Flowers', 'Machinery'. Not restricted to a master list -- the form offers existing values as suggestions but accepts anything typed.", max_length=150),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='final_destination',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Final Point of Delivery (FPOD)'),
        ),
    ]
