# Generated by Django 5.2.17 on 2026-08-11 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_alter_quotation_commodity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='shipment_type',
            field=models.CharField(blank=True, choices=[('import', 'Import'), ('export', 'Export'), ('transit', 'Transit')], help_text='Whether this shipment is an Import, Export, or Transit movement.', max_length=10),
        ),
    ]
