# Generated by Django 5.2.17 on 2026-08-13 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_historicalreferencedocument_referencedocument'),
        ('quotations', '0003_quotation_shipment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='reference_number',
        ),
        migrations.AddField(
            model_name='quotation',
            name='reference_document',
            field=models.ForeignKey(blank=True, help_text='Optional: link a supporting file (client PO, correspondence, etc.) instead of typing a reference number. Upload it under Master Data first.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='masters.referencedocument'),
        ),
    ]
